# Generated by Django 5.1.5 on 2025-01-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pharmacy_staff',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doctor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_number',
            field=models.CharField(max_length=255),
        ),
    ]
