# Generated by Django 5.1.5 on 2025-01-30 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='total_price',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='billitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalbill',
            name='doctor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalbill',
            name='gst_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospital_billing.hospitalbill'),
        ),
        migrations.AlterField(
            model_name='hospitalbill',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
