# Generated by Django 5.1.5 on 2025-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_billing', '0002_rename_total_price_billitem_rate_billitem_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbill',
            name='patient',
        ),
        migrations.AddField(
            model_name='hospitalbill',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalbill',
            name='patient_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalbill',
            name='service_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalbill',
            name='bill_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hospitalbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
